"""Add hashed password

Revision ID: 79e9da070d72
Revises: f536b2bb9bdd
Create Date: 2026-03-23 10:49:37.921761

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '79e9da070d72'
down_revision = 'f536b2bb9bdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_category'), table_name='knowledge_base_entries')
    op.drop_index(op.f('ix_kb_user_id'), table_name='knowledge_base_entries')
    op.drop_table('knowledge_base_entries')
    op.add_column('legal_strategy_blueprint', sa.Column('swot_analysis', sa.JSON(), nullable=True))
    op.add_column('legal_strategy_blueprint', sa.Column('win_probability', sa.Float(), nullable=True))
    op.add_column('legal_strategy_blueprint', sa.Column('financial_strategy', sa.JSON(), nullable=True))
    op.add_column('legal_strategy_blueprint', sa.Column('timeline_projection', sa.JSON(), nullable=True))
    op.add_column('legal_strategy_blueprint', sa.Column('penalty_forecast', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('legal_strategy_blueprint', 'penalty_forecast')
    op.drop_column('legal_strategy_blueprint', 'timeline_projection')
    op.drop_column('legal_strategy_blueprint', 'financial_strategy')
    op.drop_column('legal_strategy_blueprint', 'win_probability')
    op.drop_column('legal_strategy_blueprint', 'swot_analysis')
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_base_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_entries_pkey'))
    )
    op.create_index(op.f('ix_kb_user_id'), 'knowledge_base_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_kb_category'), 'knowledge_base_entries', ['category'], unique=False)
    # ### end Alembic commands ###
